# https://goframe.org/docs/web/server-config-file-template
server:
  address:     ":8080"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  maxHeaderBytes: "20KB" # 请求头大小限制
  clientMaxBodySize: "200MB" # 文件上传大小限制

# https://goframe.org/docs/core/glog-config
logger:
  level : "all"
  stdout: true

# https://goframe.org/docs/core/gdb-config-file
database:
  default:
    link: "mysql:root:123456@tcp(127.0.0.1:3306)/ba_boot"
    createdAt: "create_time"     # (可选)自动创建时间字段名称
    updatedAt: "update_time"   # (可选)自动更新时间字段名称
    deletedAt: "is_deleted"     # (可选)软删除时间字段名称
    timeMaintainDisabled: false # (可选)是否完全关闭时间更新特性，为true时CreatedAt/UpdatedAt/DeletedAt都将失效

# Redis 配置示例
redis:
  # 单实例配置示例1
  default:
    address: 127.0.0.1:6379
    db: 1
    pass: 123456
    idleTimeout: 600
