// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package logsOption

import (
	"Ba-Server/api/logsOption"
)

type ControllerV1 struct{}

func NewV1() logsOption.ILogsOptionV1 {
	return &ControllerV1{}
}
