// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"Ba-Server/internal/dao/internal"
)

// internalMonLogsFileDao is an internal type for wrapping the internal DAO implementation.
type internalMonLogsFileDao = *internal.MonLogsFileDao

// monLogsFileDao is the data access object for the table mon_logs_file.
// You can define custom methods on it to extend its functionality as needed.
type monLogsFileDao struct {
	internalMonLogsFileDao
}

var (
	// MonLogsFile is a globally accessible object for table mon_logs_file operations.
	MonLogsFile = monLogsFileDao{
		internal.NewMonLogsFileDao(),
	}
)

// Add your custom methods and functionality below.
