// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"Ba-Server/internal/dao/internal"
)

// internalMonLogsOperationDao is an internal type for wrapping the internal DAO implementation.
type internalMonLogsOperationDao = *internal.MonLogsOperationDao

// monLogsOperationDao is the data access object for the table mon_logs_operation.
// You can define custom methods on it to extend its functionality as needed.
type monLogsOperationDao struct {
	internalMonLogsOperationDao
}

var (
	// MonLogsOperation is a globally accessible object for table mon_logs_operation operations.
	MonLogsOperation = monLogsOperationDao{
		internal.NewMonLogsOperationDao(),
	}
)

// Add your custom methods and functionality below.
