// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"Ba-Server/internal/dao/internal"
)

// internalSysDictItemDao is an internal type for wrapping the internal DAO implementation.
type internalSysDictItemDao = *internal.SysDictItemDao

// sysDictItemDao is the data access object for the table sys_dict_item.
// You can define custom methods on it to extend its functionality as needed.
type sysDictItemDao struct {
	internalSysDictItemDao
}

var (
	// SysDictItem is a globally accessible object for table sys_dict_item operations.
	SysDictItem = sysDictItemDao{
		internal.NewSysDictItemDao(),
	}
)

// Add your custom methods and functionality below.
